version: '3.8'

services:
  security-ai-agent:
    build: .
    container_name: security-ai-agent
    ports:
      - "8989:8989"
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8989
      - FLASK_DEBUG=false
      # API Keys - set these in your environment or .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY}
      - ALIENVAULT_API_KEY=${ALIENVAULT_API_KEY}
    volumes:
      # Mount .env file if it exists
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8989/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - security-net

  # Optional: Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   container_name: security-redis
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped
  #   networks:
  #     - security-net

networks:
  security-net:
    driver: bridge 